In [19]:
!pip install --upgrade tensorflow

Collecting tensorflow
  Using cached tensorflow-2.5.0-cp37-cp37m-win_amd64.whl (422.6 MB)
Collecting astunparse~=1.6.3
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Processing c:\users\dawit\appdata\local\pip\cache\wheels\62\76\4c\aa25851149f3f6d9785f6c869387ad82b3fd37582fa8147ac6\wrapt-1.12.1-py3-none-any.whl
Collecting protobuf>=3.9.2
  Using cached protobuf-3.17.3-cp37-cp37m-win_amd64.whl (909 kB)
Requirement already satisfied, skipping upgrade: numpy~=1.19.2 in c:\users\dawit\anaconda3\envs\pythondata\lib\site-packages (from tensorflow) (1.19.5)
Collecting absl-py~=0.10
  Using cached absl_py-0.13.0-py3-none-any.whl (132 kB)
Requirement already satisfied, skipping upgrade: wheel~=0.35 in c:\users\dawit\anaconda3\envs\pythondata\lib\site-packages (from tensorflow) (0.35.1)
Collecting gast==0.4.0
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
Processing c:\users\dawit\appdata\local\pip\cache\wheels\3f\e3\ec\8a8336ff196023622fbcb36de0c5a5c218cbb24111d1d4c7f2\termcolor-1.1.0-py3-none-any.whl
Collecting tensorboard~=2.5
  Using cached tensorboard-2.5.0-py3-none-any.whl (6.0 MB)
Collecting flatbuffers~=1.12.0
  Using cached flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
Requirement already satisfied, skipping upgrade: typing-extensions~=3.7.4 in c:\users\dawit\anaconda3\envs\pythondata\lib\site-packages (from tensorflow) (3.7.4.3)
Collecting h5py~=3.1.0
  Using cached h5py-3.1.0-cp37-cp37m-win_amd64.whl (2.7 MB)
Requirement already satisfied, skipping upgrade: six~=1.15.0 in c:\users\dawit\anaconda3\envs\pythondata\lib\site-packages (from tensorflow) (1.15.0)
Collecting keras-preprocessing~=1.1.2
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
Collecting google-pasta~=0.2
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Collecting tensorflow-estimator<2.6.0,>=2.5.0rc0
  Using cached tensorflow_estimator-2.5.0-py2.py3-none-any.whl (462 kB)
Collecting opt-einsum~=3.3.0
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Collecting grpcio~=1.34.0
  Using cached grpcio-1.34.1-cp37-cp37m-win_amd64.whl (2.9 MB)
Collecting keras-nightly~=2.5.0.dev
  Using cached keras_nightly-2.5.0.dev2021032900-py2.py3-none-any.whl (1.2 MB)
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Using cached google_auth_oauthlib-0.4.5-py2.py3-none-any.whl (18 kB)
Requirement already satisfied, skipping upgrade: requests<3,>=2.21.0 in c:\users\dawit\anaconda3\envs\pythondata\lib\site-packages (from tensorboard~=2.5->tensorflow) (2.24.0)
Requirement already satisfied, skipping upgrade: setuptools>=41.0.0 in c:\users\dawit\anaconda3\envs\pythondata\lib\site-packages (from tensorboard~=2.5->tensorflow) (50.3.1.post20201107)
Collecting google-auth<2,>=1.6.3
  Using cached google_auth-1.34.0-py2.py3-none-any.whl (152 kB)
Requirement already satisfied, skipping upgrade: markdown>=2.6.8 in c:\users\dawit\anaconda3\envs\pythondata\lib\site-packages (from tensorboard~=2.5->tensorflow) (3.3.4)
Collecting tensorboard-data-server<0.7.0,>=0.6.0
  Using cached tensorboard_data_server-0.6.1-py3-none-any.whl (2.4 kB)
Collecting tensorboard-plugin-wit>=1.6.0
  Using cached tensorboard_plugin_wit-1.8.0-py3-none-any.whl (781 kB)
Requirement already satisfied, skipping upgrade: werkzeug>=0.11.15 in c:\users\dawit\anaconda3\envs\pythondata\lib\site-packages (from tensorboard~=2.5->tensorflow) (1.0.1)
Collecting cached-property; python_version < "3.8"
  Using cached cached_property-1.5.2-py2.py3-none-any.whl (7.6 kB)
Collecting requests-oauthlib>=0.7.0
  Using cached requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\dawit\anaconda3\envs\pythondata\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.5->tensorflow) (1.25.11)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in c:\users\dawit\anaconda3\envs\pythondata\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.5->tensorflow) (2020.6.20)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in c:\users\dawit\anaconda3\envs\pythondata\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.5->tensorflow) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in c:\users\dawit\anaconda3\envs\pythondata\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.5->tensorflow) (2.10)
Collecting cachetools<5.0,>=2.0.0
  Using cached cachetools-4.2.2-py3-none-any.whl (11 kB)
Collecting rsa<5,>=3.1.4; python_version >= "3.6"
  Using cached rsa-4.7.2-py3-none-any.whl (34 kB)
Collecting pyasn1-modules>=0.2.1
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Requirement already satisfied, skipping upgrade: importlib-metadata; python_version < "3.8" in c:\users\dawit\anaconda3\envs\pythondata\lib\site-packages (from markdown>=2.6.8->tensorboard~=2.5->tensorflow) (2.0.0)
Collecting oauthlib>=3.0.0
  Using cached oauthlib-3.1.1-py2.py3-none-any.whl (146 kB)
Collecting pyasn1>=0.1.3
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Requirement already satisfied, skipping upgrade: zipp>=0.5 in c:\users\dawit\anaconda3\envs\pythondata\lib\site-packages (from importlib-metadata; python_version < "3.8"->markdown>=2.6.8->tensorboard~=2.5->tensorflow) (3.4.0)
Installing collected packages: astunparse, wrapt, protobuf, absl-py, gast, termcolor, oauthlib, requests-oauthlib, cachetools, pyasn1, rsa, pyasn1-modules, google-auth, google-auth-oauthlib, tensorboard-data-server, tensorboard-plugin-wit, grpcio, tensorboard, flatbuffers, cached-property, h5py, keras-preprocessing, google-pasta, tensorflow-estimator, opt-einsum, keras-nightly, tensorflow
  Attempting uninstall: wrapt
    Found existing installation: wrapt 1.11.2
    Uninstalling wrapt-1.11.2:
      Successfully uninstalled wrapt-1.11.2
  Attempting uninstall: h5py
    Found existing installation: h5py 2.10.0
    Uninstalling h5py-2.10.0:
      Successfully uninstalled h5py-2.10.0
Successfully installed absl-py-0.13.0 astunparse-1.6.3 cached-property-1.5.2 cachetools-4.2.2 flatbuffers-1.12 gast-0.4.0 google-auth-1.34.0 google-auth-oauthlib-0.4.5 google-pasta-0.2.0 grpcio-1.34.1 h5py-3.1.0 keras-nightly-2.5.0.dev2021032900 keras-preprocessing-1.1.2 oauthlib-3.1.1 opt-einsum-3.3.0 protobuf-3.17.3 pyasn1-0.4.8 pyasn1-modules-0.2.8 requests-oauthlib-1.3.0 rsa-4.7.2 tensorboard-2.5.0 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.0 tensorflow-2.5.0 tensorflow-estimator-2.5.0 termcolor-1.1.0 wrapt-1.12.1

In [22]:
#import pandas
import keras
import pandas as pd
import numpy as np
import sqlalchemy  
from sqlalchemy import create_engine
from config import db_password
import psycopg2

In [23]:
# Postgres username, password,port and database name
POSTGRES_DBNAME = 'California_Housing' 
POSTGRES_PORT = '5432'
POSTGRES_USERNAME = 'postgres' 
POSTGRES_PASSWORD = 'db_password' 
db_string = f"postgres://postgres:{db_password}@127.0.0.1:5432/California_Housing"
California_housing = create_engine(db_string)

In [24]:
#Pull Clean_Cal_House_sale_data from PostgresSQL
Cal_House_sale_data = pd.read_sql_query('''SELECT * FROM public."Clean_Cal_House_sale_data" LIMIT 10;''', California_housing)
Cal_House_sale_data
Cal_House_sale_data.drop(['index'], axis = 1)

,MLS Number,Sale Year,Listing Year,List Price,Sale Price,Listing Date,Sale Date,Close Date,DOM,Original List Price
0,ME221068143,2021,2021,739000,760000000.0,2021-06-14,2021-06-25,7/16/2021 0:00,11,739000.0
1,EB40953507,2021,2021,1395000,206250000.0,2021-06-10,2021-06-19,7/20/2021 0:00,9,1395000.0
2,CROC21129386,2021,2021,20600000,19000000.0,2021-06-01,2021-06-01,6/18/2021 0:00,0,20600000.0
3,TM21-745464,2021,2021,15868000,15350000.0,2021-06-14,2021-06-18,7/19/2021 0:00,4,15868000.0
4,TM21-752002,2021,2021,14125000,14125000.0,2021-06-22,2021-06-22,6/22/2021 0:00,0,14125000.0
5,ML81849395,2021,2021,12800000,14000000.0,2021-06-17,2021-06-19,6/29/2021 0:00,2,12800000.0
6,TM21-762052,2021,2021,13500000,13500000.0,2021-05-26,2021-05-27,7/15/2021 0:00,1,13500000.0
7,TM21-746776,2021,2021,13450000,13350000.0,2021-06-16,2021-07-12,7/15/2021 0:00,26,13450000.0
8,TM21-747046,2021,2021,12500000,12500000.0,2021-06-09,2021-06-09,6/9/2021 0:00,0,12500000.0
9,BA321059104,2021,2021,9500000,9500000.0,2021-04-17,2021-04-18,6/28/2021 0:00,1,9500000.0

In [26]:
#Pull Clean_Cal_House_info from PostgresSQL
Cal_House_info = pd.read_sql_query('''SELECT * FROM public."Clean_Cal_House_info" LIMIT 10;''', California_housing)
Cal_House_info
Cal_House_info.drop(['index'], axis = 1)

,MLS Number,Zip Code,Street Address,Age,Sq Ft Total,Lot Size,Year Built
0,ME221068143,95819,238 San Miguel WAY,80.0,1123.0,6761.0,1941.0
1,EB40953507,94611,48 Crest Rd,73.0,1402.0,9815.0,1948.0
2,CROC21129386,92657,5 Coral,4.0,12738.0,25023.0,2017.0
3,TM21-745464,90049,850 Linda Flora DR,11.0,8177.0,40550.0,2010.0
4,TM21-752002,90049,12760 Bristol CIR,1.0,8887.0,19323.0,2020.0
5,ML81849395,94027,137 Heather DR,14.0,8803.0,39996.0,2007.0
6,TM21-762052,90210,622 Walden DR,13.0,8918.0,13074.0,2008.0
7,TM21-746776,90265,30870 Broad Beach RD,32.0,3293.0,15606.0,1989.0
8,TM21-747046,90265,25152 Malibu RD,64.0,3107.0,6644.0,1957.0
9,BA321059104,94904,111 Hill DR,83.0,6520.0,28148.0,1938.0

In [27]:
#Pull Zip_Code_County_Maching from PostgresSQL
Zip_Code_County_Maching_df = pd.read_sql_query('''SELECT * FROM public."Zip_Code_County_Maching" LIMIT 10;''', California_housing)
Zip_Code_County_Maching_df
#Zip_Code_County_Maching_df.rename(columns = {'zip_code_tabulation_area':'Zip Code'}, inplace = True)
Zip_Code_County_Maching_df.drop(['index'], axis = 1)

   zip_code_tabulation_area local_health_jurisdiction          county
0                     94063                 San Mateo       San Mateo
1                     92225                 Riverside       Riverside
2                     92273                  Imperial        Imperial
3                     92651                    Orange          Orange
4                     92801                    Orange          Orange
5                     92865                    Orange          Orange
6                     92352            San Bernardino  San Bernardino
7                     92250                  Imperial        Imperial
8                     92807                    Orange          Orange
9                     92627                    Orange          Orange

In [28]:
# Combine the Cal_House_info, Cal_House_sale_data into a single dataset.
California_Housing_df = pd.merge(Cal_House_info, Cal_House_sale_data, on=["MLS Number", "MLS Number"])
California_Housing_df.head()
#drop unecessary index
California_Housing_df['Zip Code'] = (California_Housing_df['Zip Code']).apply(int)
California_Housing_df.drop(['index_x', 'index_y'], axis = 1)

,MLS Number,Zip Code,Street Address,Age,Sq Ft Total,Lot Size,Year Built,Sale Year,Listing Year,List Price,Sale Price,Listing Date,Sale Date,Close Date,DOM,Original List Price
0,ME221068143,95819,238 San Miguel WAY,80.0,1123.0,6761.0,1941.0,2021,2021,739000,760000000.0,2021-06-14,2021-06-25,7/16/2021 0:00,11,739000.0
1,EB40953507,94611,48 Crest Rd,73.0,1402.0,9815.0,1948.0,2021,2021,1395000,206250000.0,2021-06-10,2021-06-19,7/20/2021 0:00,9,1395000.0
2,CROC21129386,92657,5 Coral,4.0,12738.0,25023.0,2017.0,2021,2021,20600000,19000000.0,2021-06-01,2021-06-01,6/18/2021 0:00,0,20600000.0
3,TM21-745464,90049,850 Linda Flora DR,11.0,8177.0,40550.0,2010.0,2021,2021,15868000,15350000.0,2021-06-14,2021-06-18,7/19/2021 0:00,4,15868000.0
4,TM21-752002,90049,12760 Bristol CIR,1.0,8887.0,19323.0,2020.0,2021,2021,14125000,14125000.0,2021-06-22,2021-06-22,6/22/2021 0:00,0,14125000.0
5,ML81849395,94027,137 Heather DR,14.0,8803.0,39996.0,2007.0,2021,2021,12800000,14000000.0,2021-06-17,2021-06-19,6/29/2021 0:00,2,12800000.0
6,TM21-762052,90210,622 Walden DR,13.0,8918.0,13074.0,2008.0,2021,2021,13500000,13500000.0,2021-05-26,2021-05-27,7/15/2021 0:00,1,13500000.0
7,TM21-746776,90265,30870 Broad Beach RD,32.0,3293.0,15606.0,1989.0,2021,2021,13450000,13350000.0,2021-06-16,2021-07-12,7/15/2021 0:00,26,13450000.0
8,TM21-747046,90265,25152 Malibu RD,64.0,3107.0,6644.0,1957.0,2021,2021,12500000,12500000.0,2021-06-09,2021-06-09,6/9/2021 0:00,0,12500000.0
9,BA321059104,94904,111 Hill DR,83.0,6520.0,28148.0,1938.0,2021,2021,9500000,9500000.0,2021-04-17,2021-04-18,6/28/2021 0:00,1,9500000.0

In [29]:
California_Housing_df.dtypes

index_x                         int64
MLS Number                     object
Zip Code                        int64
Street Address                 object
Age                           float64
Sq Ft Total                   float64
Lot Size                      float64
Year Built                    float64
index_y                         int64
Sale Year                       int64
Listing Year                    int64
List Price                      int64
Sale Price                    float64
Listing Date           datetime64[ns]
Sale Date              datetime64[ns]
Close Date                     object
DOM                             int64
Original List Price           float64
dtype: object

# Preparing Dataframe for Machine Learning Model Outcome

In [30]:
# Merge_California_Housing_df = pd.merge(California_Housing_df, Zip_Code_County_Maching_df, on=["Zip Code"], how='outer')
Merge_California_Housing_df = pd.concat([California_Housing_df, Zip_Code_County_Maching_df], axis=1, join="inner")

In [31]:
Merge_California_Housing_df
Merge_California_Housing_df = Merge_California_Housing_df.drop(['index_x', 'index_y', 'index', 'local_health_jurisdiction'], axis = 1)

In [32]:

Merge_California_Housing_df = Merge_California_Housing_df.dropna()
Merge_California_Housing_df

,MLS Number,Zip Code,Street Address,Age,Sq Ft Total,Lot Size,Year Built,Sale Year,Listing Year,List Price,Sale Price,Listing Date,Sale Date,Close Date,DOM,Original List Price,zip_code_tabulation_area,county
0,ME221068143,95819,238 San Miguel WAY,80.0,1123.0,6761.0,1941.0,2021,2021,739000,760000000.0,2021-06-14,2021-06-25,7/16/2021 0:00,11,739000.0,94063,San Mateo
1,EB40953507,94611,48 Crest Rd,73.0,1402.0,9815.0,1948.0,2021,2021,1395000,206250000.0,2021-06-10,2021-06-19,7/20/2021 0:00,9,1395000.0,92225,Riverside
2,CROC21129386,92657,5 Coral,4.0,12738.0,25023.0,2017.0,2021,2021,20600000,19000000.0,2021-06-01,2021-06-01,6/18/2021 0:00,0,20600000.0,92273,Imperial
3,TM21-745464,90049,850 Linda Flora DR,11.0,8177.0,40550.0,2010.0,2021,2021,15868000,15350000.0,2021-06-14,2021-06-18,7/19/2021 0:00,4,15868000.0,92651,Orange
4,TM21-752002,90049,12760 Bristol CIR,1.0,8887.0,19323.0,2020.0,2021,2021,14125000,14125000.0,2021-06-22,2021-06-22,6/22/2021 0:00,0,14125000.0,92801,Orange
5,ML81849395,94027,137 Heather DR,14.0,8803.0,39996.0,2007.0,2021,2021,12800000,14000000.0,2021-06-17,2021-06-19,6/29/2021 0:00,2,12800000.0,92865,Orange
6,TM21-762052,90210,622 Walden DR,13.0,8918.0,13074.0,2008.0,2021,2021,13500000,13500000.0,2021-05-26,2021-05-27,7/15/2021 0:00,1,13500000.0,92352,San Bernardino
7,TM21-746776,90265,30870 Broad Beach RD,32.0,3293.0,15606.0,1989.0,2021,2021,13450000,13350000.0,2021-06-16,2021-07-12,7/15/2021 0:00,26,13450000.0,92250,Imperial
8,TM21-747046,90265,25152 Malibu RD,64.0,3107.0,6644.0,1957.0,2021,2021,12500000,12500000.0,2021-06-09,2021-06-09,6/9/2021 0:00,0,12500000.0,92807,Orange
9,BA321059104,94904,111 Hill DR,83.0,6520.0,28148.0,1938.0,2021,2021,9500000,9500000.0,2021-04-17,2021-04-18,6/28/2021 0:00,1,9500000.0,92627,Orange

In [33]:
X = Merge_California_Housing_df.drop(columns=['Sale Price','Sale Date','Listing Date','Street Address','county','MLS Number', 'Close Date', 'zip_code_tabulation_area'])
Y = Merge_California_Housing_df[['Sale Price']]

In [34]:
print(X)

   Zip Code   Age  Sq Ft Total  Lot Size  Year Built  Sale Year  Listing Year  \
0     95819  80.0       1123.0    6761.0      1941.0       2021          2021
1     94611  73.0       1402.0    9815.0      1948.0       2021          2021
2     92657   4.0      12738.0   25023.0      2017.0       2021          2021
3     90049  11.0       8177.0   40550.0      2010.0       2021          2021
4     90049   1.0       8887.0   19323.0      2020.0       2021          2021
5     94027  14.0       8803.0   39996.0      2007.0       2021          2021
6     90210  13.0       8918.0   13074.0      2008.0       2021          2021
7     90265  32.0       3293.0   15606.0      1989.0       2021          2021
8     90265  64.0       3107.0    6644.0      1957.0       2021          2021
9     94904  83.0       6520.0   28148.0      1938.0       2021          2021

   List Price  DOM  Original List Price
0      739000   11             739000.0
1     1395000    9            1395000.0
2    20600000    0           20600000.0
3    15868000    4           15868000.0
4    14125000    0           14125000.0
5    12800000    2           12800000.0
6    13500000    1           13500000.0
7    13450000   26           13450000.0
8    12500000    0           12500000.0
9     9500000    1            9500000.0

In [35]:
print(Y)

    Sale Price
0  760000000.0
1  206250000.0
2   19000000.0
3   15350000.0
4   14125000.0
5   14000000.0
6   13500000.0
7   13350000.0
8   12500000.0
9    9500000.0

In [17]:
!pip install keras

Requirement already satisfied: keras in c:\users\dawit\anaconda3\envs\pythondata\lib\site-packages (2.4.3)
Requirement already satisfied: scipy>=0.14 in c:\users\dawit\anaconda3\envs\pythondata\lib\site-packages (from keras) (1.5.2)
Requirement already satisfied: h5py in c:\users\dawit\anaconda3\envs\pythondata\lib\site-packages (from keras) (2.10.0)
Requirement already satisfied: numpy>=1.9.1 in c:\users\dawit\anaconda3\envs\pythondata\lib\site-packages (from keras) (1.17.0)
Requirement already satisfied: pyyaml in c:\users\dawit\anaconda3\envs\pythondata\lib\site-packages (from keras) (5.3.1)
Requirement already satisfied: six in c:\users\dawit\anaconda3\envs\pythondata\lib\site-packages (from h5py->keras) (1.15.0)

In [36]:
model = keras.models.Sequential()

model.add(keras.layers.Dense(10, activation='relu', input_shape=(10,)))
model.add(keras.layers.Dense(10, activation='relu'))
model.add(keras.layers.Dense(1))

model.compile(optimizer='adam', loss='mean_squared_error')

In [37]:
model.fit(X, Y, epochs=30, callbacks=[keras.callbacks.EarlyStopping(patience=3)])

Epoch 1/30
1/1 [==============================] - 12s 12s/step - loss: 62067555942006784.0000
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss
Epoch 2/30
1/1 [==============================] - 0s 3ms/step - loss: 62065494357704704.0000
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss
Epoch 3/30
1/1 [==============================] - 0s 998us/step - loss: 62063419888500736.0000
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss
Epoch 4/30
1/1 [==============================] - 0s 3ms/step - loss: 62061336829362176.0000
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss
Epoch 5/30
1/1 [==============================] - 0s 2ms/step - loss: 62059240885321728.0000
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss
Epoch 6/30
1/1 [==============================] - 0s 3ms/step - loss: 62057144941281280.0000
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss
Epoch 7/30
1/1 [==============================] - 0s 3ms/step - loss: 62055053292208128.0000
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss
Epoch 8/30
1/1 [==============================] - 0s 7ms/step - loss: 62052953053200384.0000
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss
Epoch 9/30
1/1 [==============================] - 0s 4ms/step - loss: 62050844224258048.0000
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss
Epoch 10/30
1/1 [==============================] - 0s 2ms/step - loss: 62048696740610048.0000
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss
Epoch 11/30
1/1 [==============================] - 0s 3ms/step - loss: 62046566436831232.0000
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss
Epoch 12/30
1/1 [==============================] - 0s 2ms/step - loss: 62044418953183232.0000
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss
Epoch 13/30
1/1 [==============================] - 0s 3ms/step - loss: 62042267174567936.0000
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss
Epoch 14/30
1/1 [==============================] - 0s 74ms/step - loss: 62040093921116160.0000
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss
Epoch 15/30
1/1 [==============================] - 0s 2ms/step - loss: 62037916372697088.0000
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss
Epoch 16/30
1/1 [==============================] - 0s 4ms/step - loss: 62035738824278016.0000
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss
Epoch 17/30
1/1 [==============================] - 0s 4ms/step - loss: 62033531211087872.0000
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss
Epoch 18/30
1/1 [==============================] - 0s 3ms/step - loss: 62031310712995840.0000
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss
Epoch 19/30
1/1 [==============================] - 0s 2ms/step - loss: 62029098804838400.0000
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss
Epoch 20/30
1/1 [==============================] - 0s 996us/step - loss: 62026886896680960.0000
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss
Epoch 21/30
1/1 [==============================] - 0s 5ms/step - loss: 62024640628785152.0000
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss
Epoch 22/30
1/1 [==============================] - 0s 6ms/step - loss: 62022385770954752.0000
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss
Epoch 23/30
1/1 [==============================] - 0s 6ms/step - loss: 62020126618157056.0000
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss
Epoch 24/30
1/1 [==============================] - 0s 5ms/step - loss: 62017863170392064.0000
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss
Epoch 25/30
1/1 [==============================] - 0s 4ms/step - loss: 62015582542757888.0000
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss
Epoch 26/30
1/1 [==============================] - 0s 3ms/step - loss: 62013289030221824.0000
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss
Epoch 27/30
1/1 [==============================] - 0s 4ms/step - loss: 62011004107620352.0000
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss
Epoch 28/30
1/1 [==============================] - 0s 8ms/step - loss: 62008697710182400.0000
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss
Epoch 29/30
1/1 [==============================] - 0s 4ms/step - loss: 62006382722809856.0000
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss
Epoch 30/30
1/1 [==============================] - 0s 3ms/step - loss: 62004063440470016.0000
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss

In [38]:
test_data = np.array([94941,17,1750000,43,2215,31080.0,4,1978,2021,2021])
print(model.predict(test_data.reshape(1,10), batch_size=1))

[[643444.6]]

In [39]:
test_data = np.array([ 91401,0,975000,73,1628,6325.0,5,1948,2021,2021])
print(model.predict(test_data.reshape(1,10), batch_size=1))

[[361507.47]]